import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Example Title</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <h3>Hellow Word</h3>
  </div>
)

export default Home
